### PR TITLE
Remove suhosin test

### PR DESCRIPTION
**Pull request by ziegenberg**
### Description:

Suhosin is a PHP security extension aimed at PHP version `5.x` and Matomo 4 requires at least PHP version `7.2.5`, so this can safely go.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by snake14 — APPROVED** [review]
Seems reasonable to me. Any concerns @sgiehl ?

**Comment by sgiehl** [comment]
While Suhosin might not be relevant for PHP 7 & 8 anymore, it might be worth looking at Suhosin NG or Snuffleupagus (https://github.com/jvoisin/snuffleupagus) as replacement. Not sure if it would be worth to detect those instead.

**Comment by Findus23** [comment]
Just as a reminder, most tests of this plugin are severely outdated and might not actually give useful tips:
https://github.com/matomo-org/plugin-SecurityInfo/issues/27

**Comment by ziegenberg** [comment]
How prevalent is Snuffleupagus among the current Matomo installations out there?

**Comment by ziegenberg** [comment]
I rebased onto the current `5.x-dev` branch and switched the base branch of this PR. What is needed to finalise this?

**Comment by snake14** [comment]
> I rebased onto the current `5.x-dev` branch and switched the base branch of this PR. What is needed to finalise this?

That works for me. @sgiehl I created a new issue to look into adding a test for [snuffleupagus](https://github.com/jvoisin/snuffleupagus). Any objections to merging this PR?

**Comment by sgiehl** [comment]
No. Guess merging that should be fine.

**Pull request merged**
